package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import com.fasterxml.jackson.annotation.JsonRootName;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_LaneDataAttribute;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("Reg_LaneDataAttribute")
public class LaneDataAttribute_addGrpBReg_LaneDataAttribute extends Reg_LaneDataAttribute<LaneDataAttribute_addGrpB> {

	public LaneDataAttribute_addGrpBReg_LaneDataAttribute() {
		super(2, "LaneDataAttribute_addGrpB");
	}

	@Override
	@JsonSerialize(using = LaneDataAttribute_addGrpBReg_LaneDataAttributeValueSerializer.class)
	public LaneDataAttribute_addGrpB getRegExtValue() {
		return super.getRegExtValue();
	}

	@Override
	@JsonDeserialize(using = LaneDataAttribute_addGrpBReg_LaneDataAttributeValueDeserializer.class)
	public void setRegExtValue(LaneDataAttribute_addGrpB value) {
		super.setRegExtValue(value);
	}
}