package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import us.dot.its.jpo.ode.plugin.serialization.OpenTypeDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class LaneDataAttribute_addGrpBReg_LaneDataAttributeValueDeserializer
		extends
			OpenTypeDeserializer<LaneDataAttribute_addGrpB> {

	public LaneDataAttribute_addGrpBReg_LaneDataAttributeValueDeserializer() {
		super(LaneDataAttribute_addGrpB.class, "LaneDataAttribute_addGrpB");
	}
}