package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class LatitudeDMS2 extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = DegreesLat.DegreesLatDeserializer.class)
	private DegreesLat d;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = MinutesAngle.MinutesAngleDeserializer.class)
	private MinutesAngle m;
	@Asn1Property(tag = 2)
	@JsonDeserialize(using = SecondsAngle.SecondsAngleDeserializer.class)
	private SecondsAngle s;

	public DegreesLat getD() {
		return d;
	}

	public void setD(DegreesLat d) {
		this.d = d;
	}

	public MinutesAngle getM() {
		return m;
	}

	public void setM(MinutesAngle m) {
		this.m = m;
	}

	public SecondsAngle getS() {
		return s;
	}

	public void setS(SecondsAngle s) {
		this.s = s;
	}

	LatitudeDMS2() {
		super(false);
	}
}