package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import us.dot.its.jpo.ode.plugin.serialization.OpenTypeSerializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class NodeOffsetPointXY_addGrpBReg_NodeOffsetPointXYValueSerializer
		extends
			OpenTypeSerializer<NodeOffsetPointXY_addGrpB> {

	public NodeOffsetPointXY_addGrpBReg_NodeOffsetPointXYValueSerializer() {
		super(NodeOffsetPointXY_addGrpB.class, "regExtValue", "NodeOffsetPointXY_addGrpB");
	}
}