package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import us.dot.its.jpo.ode.plugin.types.Asn1Choice;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import java.util.Optional;
import java.util.List;
import us.dot.its.jpo.ode.plugin.types.Asn1Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
public class NodeOffsetPointXY_addGrpB extends Asn1Choice {

	@Asn1Property(tag = 0)
	private Node_LLdms_48b posA;
	@Asn1Property(tag = 1)
	private Node_LLdms_80b posB;

	NodeOffsetPointXY_addGrpB() {
		super(true);
	}

	public Node_LLdms_48b getPosA() {
		return posA;
	}

	public void setPosA(Node_LLdms_48b posA) {
		this.posA = posA;
	}

	public Node_LLdms_80b getPosB() {
		return posB;
	}

	public void setPosB(Node_LLdms_80b posB) {
		this.posB = posB;
	}

	@Override
	protected List<Optional<Asn1Type>> listTypes() {
		return null;
	}
}