package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import com.fasterxml.jackson.annotation.JsonRootName;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_NodeOffsetPointXY;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("Reg_NodeOffsetPointXY")
public class NodeOffsetPointXY_addGrpBReg_NodeOffsetPointXY extends Reg_NodeOffsetPointXY<NodeOffsetPointXY_addGrpB> {

	public NodeOffsetPointXY_addGrpBReg_NodeOffsetPointXY() {
		super(2, "NodeOffsetPointXY_addGrpB");
	}

	@Override
	@JsonSerialize(using = NodeOffsetPointXY_addGrpBReg_NodeOffsetPointXYValueSerializer.class)
	public NodeOffsetPointXY_addGrpB getRegExtValue() {
		return super.getRegExtValue();
	}

	@Override
	@JsonDeserialize(using = NodeOffsetPointXY_addGrpBReg_NodeOffsetPointXYValueDeserializer.class)
	public void setRegExtValue(NodeOffsetPointXY_addGrpB value) {
		super.setRegExtValue(value);
	}
}