package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Node_LLdms_80b extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private LongitudeDMS2 lon;
	@Asn1Property(tag = 1)
	private LatitudeDMS2 lat;

	public LongitudeDMS2 getLon() {
		return lon;
	}

	public void setLon(LongitudeDMS2 lon) {
		this.lon = lon;
	}

	public LatitudeDMS2 getLat() {
		return lat;
	}

	public void setLat(LatitudeDMS2 lat) {
		this.lat = lat;
	}

	Node_LLdms_80b() {
		super(false);
	}
}