package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import us.dot.its.jpo.ode.plugin.serialization.OpenTypeSerializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class Position3D_addGrpBReg_Position3DValueSerializer extends OpenTypeSerializer<Position3D_addGrpB> {

	public Position3D_addGrpBReg_Position3DValueSerializer() {
		super(Position3D_addGrpB.class, "regExtValue", "Position3D_addGrpB");
	}
}