package us.dot.its.jpo.ode.plugin.j2735.AddGrpB;

import us.dot.its.jpo.ode.plugin.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import us.dot.its.jpo.ode.plugin.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class SecondsAngle extends Asn1Integer {

	public SecondsAngle() {
		super(0L, 5999L);
	}

	@JsonCreator
	public SecondsAngle(long value) {
		this();
		this.value = value;
	}

	public static class SecondsAngleDeserializer extends IntegerDeserializer<SecondsAngle> {
		public SecondsAngleDeserializer() {
			super(SecondsAngle.class);
		}

		@Override
		protected SecondsAngle construct() {
			return new SecondsAngle();
		}
	}
}