package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Circle extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private Position3D center;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = Radius_B12.Radius_B12Deserializer.class)
	private Radius_B12 radius;
	@Asn1Property(tag = 2)
	private DistanceUnits units;

	public Position3D getCenter() {
		return center;
	}

	public void setCenter(Position3D center) {
		this.center = center;
	}

	public Radius_B12 getRadius() {
		return radius;
	}

	public void setRadius(Radius_B12 radius) {
		this.radius = radius;
	}

	public DistanceUnits getUnits() {
		return units;
	}

	public void setUnits(DistanceUnits units) {
		this.units = units;
	}

	Circle() {
		super(false);
	}
}