package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = DistanceUnitsSerializer.class)
@JsonDeserialize(using = DistanceUnitsDeserializer.class)
public enum DistanceUnits implements Asn1Enumerated {
	centimeter(0, "centimeter"), cm2_5(1, "cm2-5"), decimeter(2, "decimeter"), meter(3, "meter"), kilometer(4,
			"kilometer"), foot(5, "foot"), yard(6, "yard"), mile(7, "mile");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private DistanceUnits(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 7;
	}
}