package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import us.dot.its.jpo.ode.plugin.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class MergeDivergeNodeAngle extends Asn1Integer {

	public MergeDivergeNodeAngle() {
		super(-180L, 180L);
	}

	@JsonCreator
	public MergeDivergeNodeAngle(long value) {
		this();
		this.value = value;
	}

	public static class MergeDivergeNodeAngleDeserializer extends IntegerDeserializer<MergeDivergeNodeAngle> {
		public MergeDivergeNodeAngleDeserializer() {
			super(MergeDivergeNodeAngle.class);
		}

		@Override
		protected MergeDivergeNodeAngle construct() {
			return new MergeDivergeNodeAngle();
		}
	}
}