package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import us.dot.its.jpo.ode.plugin.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class MinuteOfTheYear extends Asn1Integer {

	public MinuteOfTheYear() {
		super(0L, 527040L);
	}

	@JsonCreator
	public MinuteOfTheYear(long value) {
		this();
		this.value = value;
	}

	public static class MinuteOfTheYearDeserializer extends IntegerDeserializer<MinuteOfTheYear> {
		public MinuteOfTheYearDeserializer() {
			super(MinuteOfTheYear.class);
		}

		@Override
		protected MinuteOfTheYear construct() {
			return new MinuteOfTheYear();
		}
	}
}