package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Choice;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_NodeOffsetPointLL;
import java.util.Optional;
import java.util.List;
import us.dot.its.jpo.ode.plugin.types.Asn1Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
public class NodeOffsetPointLL extends Asn1Choice {

	@Asn1Property(tag = 0, name = "node-LL1")
	@JsonProperty("node-LL1")
	private Node_LL_24B node_LL1;
	@Asn1Property(tag = 1, name = "node-LL2")
	@JsonProperty("node-LL2")
	private Node_LL_28B node_LL2;
	@Asn1Property(tag = 2, name = "node-LL3")
	@JsonProperty("node-LL3")
	private Node_LL_32B node_LL3;
	@Asn1Property(tag = 3, name = "node-LL4")
	@JsonProperty("node-LL4")
	private Node_LL_36B node_LL4;
	@Asn1Property(tag = 4, name = "node-LL5")
	@JsonProperty("node-LL5")
	private Node_LL_44B node_LL5;
	@Asn1Property(tag = 5, name = "node-LL6")
	@JsonProperty("node-LL6")
	private Node_LL_48B node_LL6;
	@Asn1Property(tag = 6, name = "node-LatLon")
	@JsonProperty("node-LatLon")
	private Node_LLmD_64b node_LatLon;
	@Asn1Property(tag = 7)
	private Reg_NodeOffsetPointLL regional;

	NodeOffsetPointLL() {
		super(false);
	}

	public Node_LL_24B getNode_LL1() {
		return node_LL1;
	}

	public void setNode_LL1(Node_LL_24B node_LL1) {
		this.node_LL1 = node_LL1;
	}

	public Node_LL_28B getNode_LL2() {
		return node_LL2;
	}

	public void setNode_LL2(Node_LL_28B node_LL2) {
		this.node_LL2 = node_LL2;
	}

	public Node_LL_32B getNode_LL3() {
		return node_LL3;
	}

	public void setNode_LL3(Node_LL_32B node_LL3) {
		this.node_LL3 = node_LL3;
	}

	public Node_LL_36B getNode_LL4() {
		return node_LL4;
	}

	public void setNode_LL4(Node_LL_36B node_LL4) {
		this.node_LL4 = node_LL4;
	}

	public Node_LL_44B getNode_LL5() {
		return node_LL5;
	}

	public void setNode_LL5(Node_LL_44B node_LL5) {
		this.node_LL5 = node_LL5;
	}

	public Node_LL_48B getNode_LL6() {
		return node_LL6;
	}

	public void setNode_LL6(Node_LL_48B node_LL6) {
		this.node_LL6 = node_LL6;
	}

	public Node_LLmD_64b getNode_LatLon() {
		return node_LatLon;
	}

	public void setNode_LatLon(Node_LLmD_64b node_LatLon) {
		this.node_LatLon = node_LatLon;
	}

	public Reg_NodeOffsetPointLL getRegional() {
		return regional;
	}

	public void setRegional(Reg_NodeOffsetPointLL regional) {
		this.regional = regional;
	}

	@Override
	protected List<Optional<Asn1Type>> listTypes() {
		return null;
	}
}