package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Node_LLmD_64b extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = Longitude.LongitudeDeserializer.class)
	private Longitude lon;
	@Asn1Property(tag = 1)
	@JsonDeserialize(using = Latitude.LatitudeDeserializer.class)
	private Latitude lat;

	public Longitude getLon() {
		return lon;
	}

	public void setLon(Longitude lon) {
		this.lon = lon;
	}

	public Latitude getLat() {
		return lat;
	}

	public void setLat(Latitude lat) {
		this.lat = lat;
	}

	Node_LLmD_64b() {
		super(false);
	}
}