package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Choice;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_NodeOffsetPointXY;
import java.util.Optional;
import java.util.List;
import us.dot.its.jpo.ode.plugin.types.Asn1Type;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
public class NodeOffsetPointXY extends Asn1Choice {

	@Asn1Property(tag = 0, name = "node-XY1")
	@JsonProperty("node-XY1")
	private Node_XY_20b node_XY1;
	@Asn1Property(tag = 1, name = "node-XY2")
	@JsonProperty("node-XY2")
	private Node_XY_22b node_XY2;
	@Asn1Property(tag = 2, name = "node-XY3")
	@JsonProperty("node-XY3")
	private Node_XY_24b node_XY3;
	@Asn1Property(tag = 3, name = "node-XY4")
	@JsonProperty("node-XY4")
	private Node_XY_26b node_XY4;
	@Asn1Property(tag = 4, name = "node-XY5")
	@JsonProperty("node-XY5")
	private Node_XY_28b node_XY5;
	@Asn1Property(tag = 5, name = "node-XY6")
	@JsonProperty("node-XY6")
	private Node_XY_32b node_XY6;
	@Asn1Property(tag = 6, name = "node-LatLon")
	@JsonProperty("node-LatLon")
	private Node_LLmD_64b node_LatLon;
	@Asn1Property(tag = 7)
	private Reg_NodeOffsetPointXY regional;

	NodeOffsetPointXY() {
		super(false);
	}

	public Node_XY_20b getNode_XY1() {
		return node_XY1;
	}

	public void setNode_XY1(Node_XY_20b node_XY1) {
		this.node_XY1 = node_XY1;
	}

	public Node_XY_22b getNode_XY2() {
		return node_XY2;
	}

	public void setNode_XY2(Node_XY_22b node_XY2) {
		this.node_XY2 = node_XY2;
	}

	public Node_XY_24b getNode_XY3() {
		return node_XY3;
	}

	public void setNode_XY3(Node_XY_24b node_XY3) {
		this.node_XY3 = node_XY3;
	}

	public Node_XY_26b getNode_XY4() {
		return node_XY4;
	}

	public void setNode_XY4(Node_XY_26b node_XY4) {
		this.node_XY4 = node_XY4;
	}

	public Node_XY_28b getNode_XY5() {
		return node_XY5;
	}

	public void setNode_XY5(Node_XY_28b node_XY5) {
		this.node_XY5 = node_XY5;
	}

	public Node_XY_32b getNode_XY6() {
		return node_XY6;
	}

	public void setNode_XY6(Node_XY_32b node_XY6) {
		this.node_XY6 = node_XY6;
	}

	public Node_LLmD_64b getNode_LatLon() {
		return node_LatLon;
	}

	public void setNode_LatLon(Node_LLmD_64b node_LatLon) {
		this.node_LatLon = node_LatLon;
	}

	public Reg_NodeOffsetPointXY getRegional() {
		return regional;
	}

	public void setRegional(Reg_NodeOffsetPointXY regional) {
		this.regional = regional;
	}

	@Override
	protected List<Optional<Asn1Type>> listTypes() {
		return null;
	}
}