package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import us.dot.its.jpo.ode.plugin.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class OffsetLL_B24 extends Asn1Integer {

	public OffsetLL_B24() {
		super(-8388608L, 8388607L);
	}

	@JsonCreator
	public OffsetLL_B24(long value) {
		this();
		this.value = value;
	}

	public static class OffsetLL_B24Deserializer extends IntegerDeserializer<OffsetLL_B24> {
		public OffsetLL_B24Deserializer() {
			super(OffsetLL_B24.class);
		}

		@Override
		protected OffsetLL_B24 construct() {
			return new OffsetLL_B24();
		}
	}
}