package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.annotation.JsonProperty;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_Position3D;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Position3D extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = Latitude.LatitudeDeserializer.class)
	private Latitude lat;
	@Asn1Property(tag = 1, name = "long")
	@JsonProperty("long")
	@JsonDeserialize(using = Longitude.LongitudeDeserializer.class)
	private Longitude long_;
	@Asn1Property(tag = 2, optional = true)
	@JsonDeserialize(using = Elevation.ElevationDeserializer.class)
	private Elevation elevation;
	@Asn1Property(tag = 3, optional = true)
	private SequenceOfRegional regional;

	public Latitude getLat() {
		return lat;
	}

	public void setLat(Latitude lat) {
		this.lat = lat;
	}

	public Longitude getLong_() {
		return long_;
	}

	public void setLong_(Longitude long_) {
		this.long_ = long_;
	}

	public Elevation getElevation() {
		return elevation;
	}

	public void setElevation(Elevation elevation) {
		this.elevation = elevation;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_Position3D> {
		SequenceOfRegional() {
			super(us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_Position3D.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	Position3D() {
		super(true);
	}
}