package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class RoadSignID extends Asn1Sequence {

	@Asn1Property(tag = 0)
	private Position3D position;
	@Asn1Property(tag = 1)
	private HeadingSlice viewAngle;
	@Asn1Property(tag = 2, optional = true)
	private MUTCDCode mutcdCode;
	@Asn1Property(tag = 3, optional = true)
	private MsgCRC crc;

	public Position3D getPosition() {
		return position;
	}

	public void setPosition(Position3D position) {
		this.position = position;
	}

	public HeadingSlice getViewAngle() {
		return viewAngle;
	}

	public void setViewAngle(HeadingSlice viewAngle) {
		this.viewAngle = viewAngle;
	}

	public MUTCDCode getMutcdCode() {
		return mutcdCode;
	}

	public void setMutcdCode(MUTCDCode mutcdCode) {
		this.mutcdCode = mutcdCode;
	}

	public MsgCRC getCrc() {
		return crc;
	}

	public void setCrc(MsgCRC crc) {
		this.crc = crc;
	}

	RoadSignID() {
		super(false);
	}
}