package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = SegmentAttributeLLSerializer.class)
@JsonDeserialize(using = SegmentAttributeLLDeserializer.class)
public enum SegmentAttributeLL implements Asn1Enumerated {
	reserved(0, "reserved"), doNotBlock(1, "doNotBlock"), whiteLine(2, "whiteLine"), mergingLaneLeft(3,
			"mergingLaneLeft"), mergingLaneRight(4, "mergingLaneRight"), curbOnLeft(5, "curbOnLeft"), curbOnRight(6,
					"curbOnRight"), loadingzoneOnLeft(7, "loadingzoneOnLeft"), loadingzoneOnRight(8,
							"loadingzoneOnRight"), turnOutPointOnLeft(9, "turnOutPointOnLeft"), turnOutPointOnRight(10,
									"turnOutPointOnRight"), adjacentParkingOnLeft(11,
											"adjacentParkingOnLeft"), adjacentParkingOnRight(12,
													"adjacentParkingOnRight"), adjacentBikeLaneOnLeft(13,
															"adjacentBikeLaneOnLeft"), adjacentBikeLaneOnRight(14,
																	"adjacentBikeLaneOnRight"), sharedBikeLane(15,
																			"sharedBikeLane"), bikeBoxInFront(16,
																					"bikeBoxInFront"), transitStopOnLeft(
																							17,
																							"transitStopOnLeft"), transitStopOnRight(
																									18,
																									"transitStopOnRight"), transitStopInLane(
																											19,
																											"transitStopInLane"), sharedWithTrackedVehicle(
																													20,
																													"sharedWithTrackedVehicle"), safeIsland(
																															21,
																															"safeIsland"), lowCurbsPresent(
																																	22,
																																	"lowCurbsPresent"), rumbleStripPresent(
																																			23,
																																			"rumbleStripPresent"), audibleSignalingPresent(
																																					24,
																																					"audibleSignalingPresent"), adaptiveTimingPresent(
																																							25,
																																							"adaptiveTimingPresent"), rfSignalRequestPresent(
																																									26,
																																									"rfSignalRequestPresent"), partialCurbIntrusion(
																																											27,
																																											"partialCurbIntrusion"), taperToLeft(
																																													28,
																																													"taperToLeft"), taperToRight(
																																															29,
																																															"taperToRight"), taperToCenterLine(
																																																	30,
																																																	"taperToCenterLine"), parallelParking(
																																																			31,
																																																			"parallelParking"), headInParking(
																																																					32,
																																																					"headInParking"), freeParking(
																																																							33,
																																																							"freeParking"), timeRestrictionsOnParking(
																																																									34,
																																																									"timeRestrictionsOnParking"), costToPark(
																																																											35,
																																																											"costToPark"), midBlockCurbPresent(
																																																													36,
																																																													"midBlockCurbPresent"), unEvenPavementPresent(
																																																															37,
																																																															"unEvenPavementPresent");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private SegmentAttributeLL(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 37;
	}
}