package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import us.dot.its.jpo.ode.plugin.serialization.SequenceOfEnumeratedDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
public class SegmentAttributeLLList extends Asn1SequenceOf<SegmentAttributeLL> {

	SegmentAttributeLLList() {
		super(SegmentAttributeLL.class, 1L, 8L);
	}

	public static class SegmentAttributeLLListDeserializer
			extends
				SequenceOfEnumeratedDeserializer<SegmentAttributeLL, SegmentAttributeLLList> {
		public SegmentAttributeLLListDeserializer() {
			super(SegmentAttributeLLList.class, SegmentAttributeLL.class);
		}

		@Override
		protected SegmentAttributeLL[] listEnumValues() {
			return SegmentAttributeLL.values();
		}

		@Override
		protected SegmentAttributeLLList construct() {
			return new SegmentAttributeLLList();
		}
	}
}