package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import us.dot.its.jpo.ode.plugin.serialization.SequenceOfEnumeratedDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
public class SegmentAttributeXYList extends Asn1SequenceOf<SegmentAttributeXY> {

	SegmentAttributeXYList() {
		super(SegmentAttributeXY.class, 1L, 8L);
	}

	public static class SegmentAttributeXYListDeserializer
			extends
				SequenceOfEnumeratedDeserializer<SegmentAttributeXY, SegmentAttributeXYList> {
		public SegmentAttributeXYListDeserializer() {
			super(SegmentAttributeXYList.class, SegmentAttributeXY.class);
		}

		@Override
		protected SegmentAttributeXY[] listEnumValues() {
			return SegmentAttributeXY.values();
		}

		@Override
		protected SegmentAttributeXYList construct() {
			return new SegmentAttributeXYList();
		}
	}
}