package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class ShapePointSet extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private Position3D anchor;
	@Asn1Property(tag = 1, optional = true)
	@JsonDeserialize(using = LaneWidth.LaneWidthDeserializer.class)
	private LaneWidth laneWidth;
	@Asn1Property(tag = 2, optional = true)
	private DirectionOfUse directionality;
	@Asn1Property(tag = 3)
	private NodeListXY nodeList;

	public Position3D getAnchor() {
		return anchor;
	}

	public void setAnchor(Position3D anchor) {
		this.anchor = anchor;
	}

	public LaneWidth getLaneWidth() {
		return laneWidth;
	}

	public void setLaneWidth(LaneWidth laneWidth) {
		this.laneWidth = laneWidth;
	}

	public DirectionOfUse getDirectionality() {
		return directionality;
	}

	public void setDirectionality(DirectionOfUse directionality) {
		this.directionality = directionality;
	}

	public NodeListXY getNodeList() {
		return nodeList;
	}

	public void setNodeList(NodeListXY nodeList) {
		this.nodeList = nodeList;
	}

	ShapePointSet() {
		super(true);
	}
}