package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = SpeedLimitTypeSerializer.class)
@JsonDeserialize(using = SpeedLimitTypeDeserializer.class)
public enum SpeedLimitType implements Asn1Enumerated {
	unknown(0, "unknown"), maxSpeedInSchoolZone(1, "maxSpeedInSchoolZone"), maxSpeedInSchoolZoneWhenChildrenArePresent(
			2, "maxSpeedInSchoolZoneWhenChildrenArePresent"), maxSpeedInConstructionZone(3,
					"maxSpeedInConstructionZone"), vehicleMinSpeed(4, "vehicleMinSpeed"), vehicleMaxSpeed(5,
							"vehicleMaxSpeed"), vehicleNightMaxSpeed(6, "vehicleNightMaxSpeed"), truckMinSpeed(7,
									"truckMinSpeed"), truckMaxSpeed(8, "truckMaxSpeed"), truckNightMaxSpeed(9,
											"truckNightMaxSpeed"), vehiclesWithTrailersMinSpeed(10,
													"vehiclesWithTrailersMinSpeed"), vehiclesWithTrailersMaxSpeed(11,
															"vehiclesWithTrailersMaxSpeed"), vehiclesWithTrailersNightMaxSpeed(
																	12, "vehiclesWithTrailersNightMaxSpeed");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private SpeedLimitType(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 12;
	}
}