package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Integer;
import com.fasterxml.jackson.annotation.JsonCreator;
import us.dot.its.jpo.ode.plugin.serialization.IntegerDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class SSPindex extends Asn1Integer {

	public SSPindex() {
		super(0L, 31L);
	}

	@JsonCreator
	public SSPindex(long value) {
		this();
		this.value = value;
	}

	public static class SSPindexDeserializer extends IntegerDeserializer<SSPindex> {
		public SSPindexDeserializer() {
			super(SSPindex.class);
		}

		@Override
		protected SSPindex construct() {
			return new SSPindex();
		}
	}
}