package us.dot.its.jpo.ode.plugin.j2735.DSRC;

//import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.asn1.Asn1Object;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_TravelerInformation;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class TravelerInformation extends Asn1Object {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = MsgCount.MsgCountDeserializer.class)
	private MsgCount msgCnt;
	@Asn1Property(tag = 1, optional = true)
	@JsonDeserialize(using = MinuteOfTheYear.MinuteOfTheYearDeserializer.class)
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 2, optional = true)
	private UniqueMSGID packetID;
	@Asn1Property(tag = 3, optional = true)
	private URL_Base urlB;
	@Asn1Property(tag = 4)
	@JacksonXmlElementWrapper(localName = "dataFrames")
	@JacksonXmlProperty(localName = "TravelerDataFrame")
	private TravelerDataFrameList dataFrames;
	@Asn1Property(tag = 5, optional = true)
	private SequenceOfRegional regional;

	public MsgCount getMsgCnt() {
		return msgCnt;
	}

	public void setMsgCnt(MsgCount msgCnt) {
		this.msgCnt = msgCnt;
	}

	public MinuteOfTheYear getTimeStamp() {
		return timeStamp;
	}

	public void setTimeStamp(MinuteOfTheYear timeStamp) {
		this.timeStamp = timeStamp;
	}

	public UniqueMSGID getPacketID() {
		return packetID;
	}

	public void setPacketID(UniqueMSGID packetID) {
		this.packetID = packetID;
	}

	public URL_Base getUrlB() {
		return urlB;
	}

	public void setUrlB(URL_Base urlB) {
		this.urlB = urlB;
	}

	public TravelerDataFrameList getDataFrames() {
		return dataFrames;
	}

	public void setDataFrames(TravelerDataFrameList dataFrames) {
		this.dataFrames = dataFrames;
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_TravelerInformation> {
		SequenceOfRegional() {
			super(us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_TravelerInformation.class, 1L, 4L);
		}
	}

	public SequenceOfRegional getRegional() {
		return regional;
	}

	public void setRegional(SequenceOfRegional regional) {
		this.regional = regional;
	}

	// TravelerInformation() {
	// 	super(true);
	// }
}