package us.dot.its.jpo.ode.plugin.j2735.DSRC;

import us.dot.its.jpo.ode.plugin.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = TravelerInfoTypeSerializer.class)
@JsonDeserialize(using = TravelerInfoTypeDeserializer.class)
public enum TravelerInfoType implements Asn1Enumerated {
	unknown(0, "unknown"), advisory(1, "advisory"), roadSignage(2, "roadSignage"), commercialSignage(3,
			"commercialSignage");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private TravelerInfoType(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 3;
	}
}