/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.ode.plugin.j2735.itis;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import us.dot.its.jpo.ode.plugin.serialization.IntegerDeserializer;
import us.dot.its.jpo.ode.plugin.types.Asn1Integer;

@JsonDeserialize(using = ITIScodes.ITIScodesDeserializer.class)
public class ITIScodes extends Asn1Integer {

	public ITIScodes() {
		super(0L, 65535L);
	}

	@JsonCreator
	public ITIScodes(long value) {
		this();
		this.value = value;
	}

	public static class ITIScodesDeserializer extends IntegerDeserializer<ITIScodes> {
		public ITIScodesDeserializer() {
			super(ITIScodes.class);
		}

		@Override
		protected ITIScodes construct() {
			return new ITIScodes();
		}
	}
}