package us.dot.its.jpo.ode.plugin.j2735.AddGrpC;

import us.dot.its.jpo.ode.plugin.types.Asn1Enumerated;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonSerialize(using = AltitudeConfidenceSerializer.class)
@JsonDeserialize(using = AltitudeConfidenceDeserializer.class)
public enum AltitudeConfidence implements Asn1Enumerated {
	alt_000_01(0, "alt-000-01"), alt_000_02(1, "alt-000-02"), alt_000_05(2, "alt-000-05"), alt_000_10(3,
			"alt-000-10"), alt_000_20(4, "alt-000-20"), alt_000_50(5, "alt-000-50"), alt_001_00(6,
					"alt-001-00"), alt_002_00(7, "alt-002-00"), alt_005_00(8, "alt-005-00"), alt_010_00(9,
							"alt-010-00"), alt_020_00(10, "alt-020-00"), alt_050_00(11, "alt-050-00"), alt_100_00(12,
									"alt-100-00"), alt_200_00(13,
											"alt-200-00"), outOfRange(14, "outOfRange"), unavailable(15, "unavailable");

	private final int index;
	private final String name;

	public int getIndex() {
		return index;
	}

	public String getName() {
		return name;
	}

	public boolean hasExtensionMarker() {
		return false;
	}

	private AltitudeConfidence(int index, String name) {
		this.index = index;
		this.name = name;
	}

	public int maxIndex() {
		return 15;
	}
}