package us.dot.its.jpo.ode.plugin.j2735.AddGrpC;

import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Altitude extends Asn1Sequence {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = AltitudeValue.AltitudeValueDeserializer.class)
	private AltitudeValue value;
	@Asn1Property(tag = 1)
	private AltitudeConfidence confidence;

	public AltitudeValue getValue() {
		return value;
	}

	public void setValue(AltitudeValue value) {
		this.value = value;
	}

	public AltitudeConfidence getConfidence() {
		return confidence;
	}

	public void setConfidence(AltitudeConfidence confidence) {
		this.confidence = confidence;
	}

	Altitude() {
		super(false);
	}
}