package us.dot.its.jpo.ode.plugin.j2735.AddGrpC;

import com.fasterxml.jackson.annotation.JsonRootName;
import us.dot.its.jpo.ode.plugin.j2735.REGION.Reg_Position3D;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
@JsonRootName("Reg_Position3D")
public class Position3D_addGrpCReg_Position3D extends Reg_Position3D<Position3D_addGrpC> {

	public Position3D_addGrpCReg_Position3D() {
		super(3, "Position3D_addGrpC");
	}

	@Override
	@JsonSerialize(using = Position3D_addGrpCReg_Position3DValueSerializer.class)
	public Position3D_addGrpC getRegExtValue() {
		return super.getRegExtValue();
	}

	@Override
	@JsonDeserialize(using = Position3D_addGrpCReg_Position3DValueDeserializer.class)
	public void setRegExtValue(Position3D_addGrpC value) {
		super.setRegExtValue(value);
	}
}