package us.dot.its.jpo.ode.plugin.j2735.AddGrpC;

import us.dot.its.jpo.ode.plugin.serialization.OpenTypeDeserializer;

/**
 * 
 * <p>
 * This source code was generated by a tool. Manual edits are futile.
 * </p>
 * <p>
 * asn1jvm v1.0-SNAPSHOT
 * </p>
 * <p>
 * ASN.1 source files:
 * </p>
 * 
 * <pre>
 * J2735_201603DA.ASN
 * </pre>
 * 
 */
public class Position3D_addGrpCReg_Position3DValueDeserializer extends OpenTypeDeserializer<Position3D_addGrpC> {

	public Position3D_addGrpCReg_Position3DValueDeserializer() {
		super(Position3D_addGrpC.class, "Position3D_addGrpC");
	}
}