/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.ode.plugin.j2735.common;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.j2735.region.Reg_NodeOffsetPointXY;
import us.dot.its.jpo.ode.plugin.types.Asn1Choice;

@Getter
@Setter
@JsonInclude(Include.NON_NULL)
public class NodeOffsetPointXY extends Asn1Choice {

	@Asn1Property(tag = 0, name = "node-XY1")
	@JsonProperty("node-XY1")
	private Node_XY_20b node_XY1;
	@Asn1Property(tag = 1, name = "node-XY2")
	@JsonProperty("node-XY2")
	private Node_XY_22b node_XY2;
	@Asn1Property(tag = 2, name = "node-XY3")
	@JsonProperty("node-XY3")
	private Node_XY_24b node_XY3;
	@Asn1Property(tag = 3, name = "node-XY4")
	@JsonProperty("node-XY4")
	private Node_XY_26b node_XY4;
	@Asn1Property(tag = 4, name = "node-XY5")
	@JsonProperty("node-XY5")
	private Node_XY_28b node_XY5;
	@Asn1Property(tag = 5, name = "node-XY6")
	@JsonProperty("node-XY6")
	private Node_XY_32b node_XY6;
	@Asn1Property(tag = 6, name = "node-LatLon")
	@JsonProperty("node-LatLon")
	private Node_LLmD_64b node_LatLon;
	@Asn1Property(tag = 7, name = "regional")
	@JsonProperty("regional")
	private Reg_NodeOffsetPointXY regional;

	NodeOffsetPointXY() {
		super(false);
	}
}