/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.ode.plugin.j2735.common;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import us.dot.its.jpo.ode.plugin.serialization.SequenceOfEnumeratedDeserializer;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;

@JsonInclude(Include.NON_NULL)
public class NodeAttributeXYList extends Asn1SequenceOf<NodeAttributeXY> {

	NodeAttributeXYList() {
		super(NodeAttributeXY.class, 1L, 8L);
	}

	public static class NodeAttributeXYListDeserializer
			extends
				SequenceOfEnumeratedDeserializer<NodeAttributeXY, NodeAttributeXYList> {
		public NodeAttributeXYListDeserializer() {
			super(NodeAttributeXYList.class, NodeAttributeXY.class);
		}

		@Override
		protected NodeAttributeXY[] listEnumValues() {
			return NodeAttributeXY.values();
		}

		@Override
		protected NodeAttributeXYList construct() {
			return new NodeAttributeXYList();
		}
	}
}