/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.ode.plugin.j2735.common;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.j2735.region.Reg_NodeAttributeSetXY;
import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class NodeAttributeSetXY extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "localNode", optional = true)
	@JsonProperty("localNode")
	@JsonDeserialize(using = NodeAttributeXYList.NodeAttributeXYListDeserializer.class)
	private NodeAttributeXYList localNode;
	@Asn1Property(tag = 1, name = "disabled", optional = true)
	@JsonProperty("disabled")
	@JsonDeserialize(using = SegmentAttributeXYList.SegmentAttributeXYListDeserializer.class)
	private SegmentAttributeXYList disabled;
	@Asn1Property(tag = 2, name = "enabled", optional = true)
	@JsonProperty("enabled")
	@JsonDeserialize(using = SegmentAttributeXYList.SegmentAttributeXYListDeserializer.class)
	private SegmentAttributeXYList enabled;
	@Asn1Property(tag = 3, name = "data", optional = true)
	@JsonProperty("data")
	@JsonSerialize(using = LaneDataAttributeList.LaneDataAttributeListSerializer.class)
	@JsonDeserialize(using = LaneDataAttributeList.LaneDataAttributeListDeserializer.class)
	private LaneDataAttributeList data;
	@Asn1Property(tag = 4, name = "dWidth", optional = true)
	@JsonProperty("dWidth")
	private Offset_B10 dWidth;
	@Asn1Property(tag = 5, name = "dElevation", optional = true)
	@JsonProperty("dElevation")
	private Offset_B10 dElevation;
	@Asn1Property(tag = 6, name = "regional", optional = true)
	@JsonProperty("regional")
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_NodeAttributeSetXY> {
		SequenceOfRegional() {
			super(Reg_NodeAttributeSetXY.class, 1L, 4L);
		}
	}

	NodeAttributeSetXY() {
		super(true);
	}
}