package us.dot.its.jpo.ode.plugin.j2735;

public enum J2735EssPrecipSituation {
	OTHER,
	UNKNOWN,
	NOPRECIPITATION,
	UNIDENTIFIEDSLIGHT,
	UNIDENTIFIEDMODERATE,
	UNIDENTIFIEDHEAVY,
	SNOWSLIGHT,
	SNOWMODERATE,
	SNOWHEAVY,
	RAINSLIGHT,
	RAINMODERATE,
	RAINHEAVY,
	FROZENPRECIPITATIONSLIGHT,
	FROZENPRECIPITATIONMODERATE,
	FROZENPRECIPITATIONHEAVY
}
