package us.dot.its.jpo.ode.plugin.j2735;


public enum J2735IntersectionStatusObject {
	MANUALCONTROLISENABLED,
	STOPTIMEISACTIVATED,
	FAILUREFLASH,
	PREEMPTISACTIVE,
	SIGNALPRIORITYISACTIVE,
	FIXEDTIMEOPERATION,
	TRAFFICDEPENDENTOPERATION,
	STANDBYOPERATION,
	FAILUREMODE,
	OFF,
	RECENTMAPMESSAGEUPDATE,
	RECENTCHANGEINMAPASSIGNEDLANESIDSUSED,
	NOVALIDMAPISAVAILABLEATTHISTIME,
	NOVALIDSPATISAVAILABLEATTHISTIME
}
