package us.dot.its.jpo.ode.plugin.j2735;

public enum J2735SegmentAttribute {
	 reserved                  ,  
	   doNotBlock                , 
	   whiteLine                 ,
	   mergingLaneLeft           ,  
	   mergingLaneRight          ,	   
	   curbOnLeft                ,  
	   curbOnRight               ,	   
	   loadingzoneOnLeft         , 
	   loadingzoneOnRight        ,	   
	   turnOutPointOnLeft        ,  
	   turnOutPointOnRight       ,	   
	   adjacentParkingOnLeft     , 
	   adjacentParkingOnRight    ,
	   adjacentBikeLaneOnLeft    , 
	   adjacentBikeLaneOnRight   ,
	   sharedBikeLane            , 
	   bikeBoxInFront            ,
	   transitStopOnLeft         , 	                               
	   transitStopOnRight        ,
	   transitStopInLane         , 	                               
	   sharedWithTrackedVehicle  ,
	   safeIsland                , 
	   lowCurbsPresent           , 
	   rumbleStripPresent        , 
	   audibleSignalingPresent   , 
	   adaptiveTimingPresent     , 
	   rfSignalRequestPresent    ,
	   partialCurbIntrusion      , 
	   taperToLeft               , 
	   taperToRight              , 
	   taperToCenterLine         , 
	   headInParking             , 
	   freeParking               , 
	   timeRestrictionsOnParking ,                                
	   costToPark                , 
	   midBlockCurbPresent       , 
	   unEvenPavementPresent     
}
