package us.dot.its.jpo.ode.plugin.j2735;

public enum J2735PublicSafetyDirectingTrafficSubType {
    UNAVAILABLE,
    POLICEANDTRAFFICOFFICERS, 
    TRAFFICCONTROLPERSONS, 
    CIVILDEFENSENATIONALGUARDMILITARYPOLICE,
    EMERGENCYORGANIZATIONPERSONNEL,
    HIGHWAYSERVICEVEHICLEPERSONNEL
}