package us.dot.its.jpo.ode.plugin.j2735;


public enum J2735MovementPhaseState {
		UNAVAILABLE,
		DARK,
		STOP_THEN_PROCEED,
		STOP_AND_REMAIN,
		PRE_MOVEMENT,
		PERMISSIVE_MOVEMENT_ALLOWED,
		PROTECTED_MOVEMENT_ALLOWED,
		PERMISSIVE_CLEARANCE,
		PROTECTED_CLEARANCE,
		CAUTION_CONFLICTING_TRAFFIC
}
