package us.dot.its.jpo.ode.plugin.j2735;

public enum J2735ResponderGroupAffected {
	EMERGENCY_VEHICLE_UNITS,
	FEDERAL_LAW_ENFORCEMENT_UNITS,
	STATE_POLICE_UNITS,
	COUNTY_POLICE_UNITS,
	LOCAL_POLICE_UNITS,
	AMBULANCE_UNITS,
	RESCUE_UNITS,
	FIRE_UNITS,
	HAZMAT_UNITS,
	LIGHT_TOW_UNIT,
	HEAVY_TOW_UNIT,
	FREEWAY_SERVICE_PATROLS,
	TRANSPORTATION_RESPONSE_UNITS,
	PRIVATE_CONTRACTOR_RESPONSE_UNITS

}
