package us.dot.its.jpo.ode.plugin.j2735;

public enum J2735VehicleEventFlag {
	EVENTHAZARDLIGHTS,
	EVENTSTOPLINEVIOLATION,
	EVENTABSACTIVATED,
	EVENTTRACTIONCONTROLLOSS,
	EVENTSTABILITYCONTROLACTIVATED,
	EVENTHAZARDOUSMATERIALS,
	EVENTRESERVED1,
	EVENTHARDBREAKING,
	EVENTLIGHTSCHANGED,
	EVENTWIPERSCHANGED,
	EVENTFLATTIRE,
	EVENTDISABLEDVEHICLE,
	EVENTAIRBAGDEPLOYMENT
}
