package us.dot.its.jpo.ode.plugin.j2735.travelerinformation;

import us.dot.its.jpo.ode.plugin.j2735.common.*;
import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.types.Asn1Boolean;
import us.dot.its.jpo.ode.plugin.types.Asn1Choice;
import java.util.List;
import java.util.Optional;
import us.dot.its.jpo.ode.plugin.types.Asn1Type;
import us.dot.its.jpo.ode.plugin.j2735.region.Reg_GeographicalPath;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

/**
 * 
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class GeographicalPath extends Asn1Sequence {

	@Asn1Property(tag = 0, optional = true)
	private DescriptiveName name;
	@Asn1Property(tag = 1, optional = true)
	private RoadSegmentReferenceID id;
	@Asn1Property(tag = 2, optional = true)
	private Position3D anchor;
	@Asn1Property(tag = 3, optional = true)
	@JsonDeserialize(using = LaneWidth.LaneWidthDeserializer.class)
	private LaneWidth laneWidth;
	@Asn1Property(tag = 4, optional = true)
	private DirectionOfUse directionality;
	@Asn1Property(tag = 5, optional = true)
	private Asn1Boolean closedPath;
	@Asn1Property(tag = 6, optional = true)
	private HeadingSlice direction;
	@Asn1Property(tag = 7, optional = true)
	private DescriptionChoice description;
	@Asn1Property(tag = 8, optional = true)
	private SequenceOfRegional regional;

	@Getter
	@Setter
	@JsonInclude(Include.NON_NULL)
	public static class DescriptionChoice extends Asn1Choice {
		@Asn1Property(tag = 0)
		private OffsetSystem path;
		@Asn1Property(tag = 1)
		private GeometricProjection geometry;
		@Asn1Property(tag = 2)
		private ValidRegion oldRegion;

		DescriptionChoice() {
			super(true);
		}

		@Override
		protected List<Optional<Asn1Type>> listTypes() {
			return null;
		}
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_GeographicalPath> {
		SequenceOfRegional() {
			super(Reg_GeographicalPath.class, 1L, 4L);
		}
	}

	GeographicalPath() {
		super(true);
	}
}