package us.dot.its.jpo.ode.plugin.j2735.travelerinformation;

import us.dot.its.jpo.ode.plugin.asn1.Asn1Object;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.j2735.region.Reg_TravelerInformation;
import us.dot.its.jpo.ode.plugin.j2735.common.MinuteOfTheYear;
import us.dot.its.jpo.ode.plugin.j2735.common.MsgCount;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;

/*
 * EDITED - Changed base class to Asn1Object
 */

/**
 * EDITED - Change base class to Asn1Object
 *******************************************************************************
 *
 * This source file was generated by a tool. Beware manual edits might be
 * overwritten in future releases. asn1jvm v1.0-SNAPSHOT
 *
 *******************************************************************************
 * Copyright 2024 USDOT
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 ******************************************************************************
 * 
 */
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class TravelerInformation extends Asn1Object {

	@Asn1Property(tag = 0)
	@JsonDeserialize(using = MsgCount.MsgCountDeserializer.class)
	private MsgCount msgCnt;
	@Asn1Property(tag = 1, optional = true)
	@JsonDeserialize(using = MinuteOfTheYear.MinuteOfTheYearDeserializer.class)
	private MinuteOfTheYear timeStamp;
	@Asn1Property(tag = 2, optional = true)
	private UniqueMSGID packetID;
	@Asn1Property(tag = 3, optional = true)
	private URL_Base urlB;
	@Asn1Property(tag = 4)
	@JacksonXmlElementWrapper(localName = "dataFrames")
	@JacksonXmlProperty(localName = "TravelerDataFrame")
	private TravelerDataFrameList dataFrames;
	@Asn1Property(tag = 5, optional = true)
	private SequenceOfRegional regional;

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegional extends Asn1SequenceOf<Reg_TravelerInformation> {
		SequenceOfRegional() {
			super(Reg_TravelerInformation.class, 1L, 4L);
		}
	}

//	TravelerInformation() {
//		super(true);
//	}
}