/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.ode.plugin.j2735.travelerinformation;

import com.fasterxml.jackson.annotation.JsonAlias;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.j2735.common.DYear;
import us.dot.its.jpo.ode.plugin.j2735.common.FurtherInfoID;
import us.dot.its.jpo.ode.plugin.j2735.common.MinuteOfTheYear;
import us.dot.its.jpo.ode.plugin.j2735.common.SSPindex;
import us.dot.its.jpo.ode.plugin.j2735.itis.ITIScodesAndText;
import us.dot.its.jpo.ode.plugin.serialization.NestedSequenceOfDeserializer;
import us.dot.its.jpo.ode.plugin.serialization.NestedSequenceOfSerializer;
import us.dot.its.jpo.ode.plugin.types.Asn1Choice;
import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;
import us.dot.its.jpo.ode.plugin.types.Asn1SequenceOf;

/*
 * EDITED -> doNotUse1, doNotUse2, doNotUse3, doNotUse4, durationTime fields.
 */

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class TravelerDataFrame extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "doNotUse1")
	@JsonProperty("doNotUse1")
	@JsonAlias({"sspTimRights", "notUsed"})
	private SSPindex doNotUse1;
	@Asn1Property(tag = 1, name = "frameType")
	@JsonProperty("frameType")
	private TravelerInfoType frameType;
	@Asn1Property(tag = 2, name = "msgId")
	@JsonProperty("msgId")
	private MsgIdChoice msgId;
	@Asn1Property(tag = 3, name = "startYear", optional = true)
	@JsonProperty("startYear")
	private DYear startYear;
	@Asn1Property(tag = 4, name = "startTime")
	@JsonProperty("startTime")
	private MinuteOfTheYear startTime;
	@Asn1Property(tag = 5, name = "durationTime")
	@JsonProperty("durationTime")
	@JsonAlias("duratonTime")
	private MinutesDuration durationTime;
	@Asn1Property(tag = 6, name = "priority")
	@JsonProperty("priority")
	private SignPrority priority;
	@Asn1Property(tag = 7, name = "doNotUse2")
	@JsonProperty("doNotUse2")
	@JsonAlias({"sspLocationRights", "notUsed1"})
	private SSPindex doNotUse2;
	@Asn1Property(tag = 8, name = "regions")
	@JsonProperty("regions")
	private SequenceOfRegions regions;
	@Asn1Property(tag = 9, name = "doNotUse3")
	@JsonProperty("doNotUse3")
	@JsonAlias({"sspMsgContent", "sspMsgRights1", "notUsed2"})
	private SSPindex doNotUse3;
	@Asn1Property(tag = 10, name = "doNotUse4")
	@JsonProperty("doNotUse4")
	@JsonAlias({"sspMsgTypes", "sspMsgRights2", "notUsed3"})
	private SSPindex doNotUse4;
	@Asn1Property(tag = 11, name = "content")
	@JsonProperty("content")
	private ContentChoice content;
	@Asn1Property(tag = 12, name = "url", optional = true)
	@JsonProperty("url")
	private URL_Short url;

	@Getter
	@Setter
	@JsonInclude(Include.NON_NULL)
	public static class MsgIdChoice extends Asn1Choice {
		@Asn1Property(tag = 0, name = "furtherInfoID")
		@JsonProperty("furtherInfoID")
		private FurtherInfoID furtherInfoID;
		@Asn1Property(tag = 1, name = "roadSignID")
		@JsonProperty("roadSignID")
		private RoadSignID roadSignID;

		MsgIdChoice() {
			super(false);
		}
	}

	@JsonInclude(Include.NON_NULL)
	public static class SequenceOfRegions extends Asn1SequenceOf<GeographicalPath> {
		SequenceOfRegions() {
			super(GeographicalPath.class, 1L, 16L);
		}
	}

	@Getter
	@Setter
	@JsonInclude(Include.NON_NULL)
	public static class ContentChoice extends Asn1Choice {
		@Asn1Property(tag = 0, name = "advisory")
		@JsonProperty("advisory")
		@JsonDeserialize(using = AdvisoryDeserializer.class)
		@JsonSerialize(using = AdvisorySerializer.class)
		private ITIScodesAndText advisory;
		@Asn1Property(tag = 1, name = "workZone")
		@JsonProperty("workZone")
		@JsonDeserialize(using = WorkZoneDeserializer.class)
		@JsonSerialize(using = WorkZoneSerializer.class)
		private WorkZone workZone;
		@Asn1Property(tag = 2, name = "genericSign")
		@JsonProperty("genericSign")
		@JsonDeserialize(using = GenericSignDeserializer.class)
		@JsonSerialize(using = GenericSignSerializer.class)
		private GenericSignage genericSign;
		@Asn1Property(tag = 3, name = "speedLimit")
		@JsonProperty("speedLimit")
		@JsonDeserialize(using = SpeedLimitDeserializer.class)
		@JsonSerialize(using = SpeedLimitSerializer.class)
		private SpeedLimit speedLimit;
		@Asn1Property(tag = 4, name = "exitService")
		@JsonProperty("exitService")
		@JsonDeserialize(using = ExitServiceDeserializer.class)
		@JsonSerialize(using = ExitServiceSerializer.class)
		private ExitService exitService;

		ContentChoice() {
			super(false);
		}
	}

	TravelerDataFrame() {
		super(true);
	}

	public static class AdvisoryDeserializer extends NestedSequenceOfDeserializer<ITIScodesAndText> {
		public AdvisoryDeserializer() {
			super(ITIScodesAndText.class, "SEQUENCE");
		}
	}

	public static class AdvisorySerializer extends NestedSequenceOfSerializer<ITIScodesAndText> {
		public AdvisorySerializer() {
			super(ITIScodesAndText.class, "SEQUENCE");
		}
	}

	public static class WorkZoneDeserializer extends NestedSequenceOfDeserializer<WorkZone> {
		public WorkZoneDeserializer() {
			super(WorkZone.class, "SEQUENCE");
		}
	}

	public static class WorkZoneSerializer extends NestedSequenceOfSerializer<WorkZone> {
		public WorkZoneSerializer() {
			super(WorkZone.class, "SEQUENCE");
		}
	}

	public static class GenericSignDeserializer extends NestedSequenceOfDeserializer<GenericSignage> {
		public GenericSignDeserializer() {
			super(GenericSignage.class, "SEQUENCE");
		}
	}

	public static class GenericSignSerializer extends NestedSequenceOfSerializer<GenericSignage> {
		public GenericSignSerializer() {
			super(GenericSignage.class, "SEQUENCE");
		}
	}

	public static class SpeedLimitDeserializer extends NestedSequenceOfDeserializer<SpeedLimit> {
		public SpeedLimitDeserializer() {
			super(SpeedLimit.class, "SEQUENCE");
		}
	}

	public static class SpeedLimitSerializer extends NestedSequenceOfSerializer<SpeedLimit> {
		public SpeedLimitSerializer() {
			super(SpeedLimit.class, "SEQUENCE");
		}
	}

	public static class ExitServiceDeserializer extends NestedSequenceOfDeserializer<ExitService> {
		public ExitServiceDeserializer() {
			super(ExitService.class, "SEQUENCE");
		}
	}

	public static class ExitServiceSerializer extends NestedSequenceOfSerializer<ExitService> {
		public ExitServiceSerializer() {
			super(ExitService.class, "SEQUENCE");
		}
	}
}