/*==============================================================================
 *
 * This source file was generated by a tool.
 * Beware manual edits might be overwritten in future releases.
 * asn1jvm v1.0-SNAPSHOT
 *
 *------------------------------------------------------------------------------
 * Copyright 2024 USDOT
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License.  You may obtain a copy
 * of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *============================================================================*/

package us.dot.its.jpo.ode.plugin.j2735.travelerinformation;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import us.dot.its.jpo.ode.plugin.annotations.Asn1Property;
import us.dot.its.jpo.ode.plugin.j2735.common.Extent;
import us.dot.its.jpo.ode.plugin.j2735.common.HeadingSlice;
import us.dot.its.jpo.ode.plugin.types.Asn1Choice;
import us.dot.its.jpo.ode.plugin.types.Asn1Sequence;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@Getter
@Setter
public class ValidRegion extends Asn1Sequence {

	@Asn1Property(tag = 0, name = "direction")
	@JsonProperty("direction")
	private HeadingSlice direction;
	@Asn1Property(tag = 1, name = "extent", optional = true)
	@JsonProperty("extent")
	private Extent extent;
	@Asn1Property(tag = 2, name = "area")
	@JsonProperty("area")
	private AreaChoice area;

	@Getter
	@Setter
	@JsonInclude(Include.NON_NULL)
	public static class AreaChoice extends Asn1Choice {
		@Asn1Property(tag = 0, name = "shapePointSet")
		@JsonProperty("shapePointSet")
		private ShapePointSet shapePointSet;
		@Asn1Property(tag = 1, name = "circle")
		@JsonProperty("circle")
		private Circle circle;
		@Asn1Property(tag = 2, name = "regionPointSet")
		@JsonProperty("regionPointSet")
		private RegionPointSet regionPointSet;

		AreaChoice() {
			super(false);
		}
	}

	ValidRegion() {
		super(false);
	}
}